from __future__ import annotations

from typing import Dict

# OCR·입력 별칭 → 표준 은행명(BANK_ACCOUNT_PATTERNS 키). 조회는 casefold().
BANK_NAME_ALIASES: Dict[str, str] = {
    "국민": "국민은행",
    "kb": "국민은행",
    "kb국민": "국민은행",
    "kb국민은행": "국민은행",
    "신한": "신한은행",
    "shinhan": "신한은행",
    "shinhan은행": "신한은행",
    "shinhanbank": "신한은행",
    "우리": "우리은행",
    "woori": "우리은행",
    "wooribank": "우리은행",
    "하나": "하나은행",
    "hana": "하나은행",
    "hanabank": "하나은행",
    "농협": "농협은행",
    "수협": "수협은행",
    "nh": "농협은행",
    "nh농협": "농협은행",
    "nh농협은행": "농협은행",
    "ibk": "IBK기업은행",
    "새마을": "새마을금고",
    "mg": "새마을금고",
    "sc": "SC제일은행",
    "sc제일": "SC제일은행",
    "카카오": "카카오뱅크",
    "kakao": "카카오뱅크",
    "kakaobank": "카카오뱅크",
    "kbank": "케이뱅크",
    "k뱅크": "케이뱅크",
    "토스": "토스뱅크",
    "toss": "토스뱅크",
    "tossbank": "토스뱅크",
    "우편": "우체국",
    "bnk": "부산은행",
    "부산": "부산은행",
    "제주": "제주은행",
    "씨티": "씨티은행",
    "citi": "씨티은행",
    "kdb": "KDB산업은행",
    "산업은행": "KDB산업은행",
}
