server {
    listen 80;
    server_name localhost;

    # 1. 프론트엔드 화면
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. AI 서버 전용 라우팅 (FastAPI)
    # 주소창에 /api/ai/ 가 보이면 이쪽으로!
    location /api/ai/ {
        proxy_pass http://palipay-ai-service:80;  # 마지막에 / 를 붙이면 /api/ai/ 부분을 떼고 전달합니다.

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. 일반 백엔드 API 라우팅 (Spring Boot)
    location /api/ {
        proxy_pass http://palipay-backend-svc:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}