server {
    listen 80;
    server_name localhost;

    location / {
        # 플러터 빌드 파일들이 있는 경로
        root /usr/share/nginx/html;
        index index.html index.htm;

        # 핵심: 파일이나 폴더가 없으면 무조건 /index.html 로 돌려보내라!
        try_files $uri $uri/ /index.html;
    }
}